const mer = @import("mer");
const lib = @import("lib");

pub const meta: mer.Meta = .{ .title = "Data and privacy settings" };

pub fn render(req: mer.Request) mer.Response {
    if (lib.m3.gate(req, "Data and privacy")) |response| return response;
    const demo = lib.m3.isExplicitDemo(req);
    var buf = lib.ui.buildHtml(req.allocator);
    const w = &buf.writer;
    lib.m3.demoMarker(req, w) catch return mer.internalError("data settings render failed");
    lib.settings_ui.heading(req, w, "data", "Ownership and portability", "Data & privacy", "Export your work or permanently remove locally owned account data.", demo) catch return mer.internalError("data settings render failed");
    w.writeAll("<div class=\"cp-settings-column\"><section class=\"cp-settings-section cp-export-options\"><header><div><p class=\"eyebrow\">Portable copies</p><h2>Export your workspace</h2><p>Downloads are assembled only after you request them.</p></div></header><article><div><h3>Wiki Markdown ZIP</h3><p>Current Wiki pages and their readable Markdown.</p></div><button class=\"cp-btn cp-btn-ghost\" type=\"button\" data-wiki-export>Download Wiki</button></article><article><div><h3>Workspace archive</h3><p>Profile, preferences, readable source text, Wiki revisions, guides, cards, evidence, papers, and non-secret provider settings.</p><small>Passwords, tokens, API keys, embeddings, and internal request records are excluded.</small></div>") catch return mer.internalError("data settings render failed");
    if (demo) w.writeAll("<button class=\"cp-btn cp-btn-ghost\" type=\"button\" disabled>Download workspace archive</button>") catch return mer.internalError("data settings render failed") else w.writeAll("<form method=\"post\" action=\"/api/settings\" data-settings-form data-download><input type=\"hidden\" name=\"action\" value=\"account.export\"><label class=\"cp-field\"><span>Confirm current password</span><input type=\"password\" name=\"current_password\" autocomplete=\"current-password\" required></label><button class=\"cp-btn cp-btn-ghost\" type=\"submit\">Download workspace archive</button><p class=\"cp-form-status\" role=\"status\" tabindex=\"-1\"></p></form>") catch return mer.internalError("data settings render failed");
    w.writeAll("</article></section><section class=\"cp-settings-section cp-danger-zone\"><header><div><p class=\"eyebrow\">Permanent action</p><h2>Delete account</h2><p>Deletes all data owned by this account in WikiBase and revokes every login.</p></div></header><p>Canvas originals and data retained by external providers remain outside WikiBase and cannot be deleted here.</p>") catch return mer.internalError("data settings render failed");
    if (!demo) w.writeAll("<form method=\"post\" action=\"/api/settings\" data-settings-form data-delete-account><input type=\"hidden\" name=\"action\" value=\"account.delete\"><label class=\"cp-field\"><span>Current password</span><input type=\"password\" name=\"current_password\" autocomplete=\"current-password\" required></label><label class=\"cp-field\"><span>Type DELETE to confirm</span><input name=\"confirmation\" pattern=\"DELETE\" autocomplete=\"off\" required></label><label class=\"cp-check-row\"><input type=\"checkbox\" name=\"final_confirmation\" required><span>I understand this permanently removes my WikiBase account.</span></label><button class=\"cp-btn cp-btn-danger\" type=\"submit\">Delete my account</button><p class=\"cp-form-status\" role=\"status\" tabindex=\"-1\"></p></form>") catch return mer.internalError("data settings render failed");
    w.writeAll("</section></div><script src=\"/m3.js?v=20260722\" defer></script><script src=\"/settings.js?v=20260724\" defer></script>") catch return mer.internalError("data settings render failed");
    return lib.m3.privateForSession(req, lib.ui.htmlResponse(&buf));
}
